### ISSUE TITLE
I am ink does not always reliably start with head tracking

### ISSUE THREAD

**Issue by caseyyee** [MozVR/webvr-demos#3]
This might not be a big deal if we replace this demo.  Just something to look into.

**Comment by cvan** [comment]
is this on Windows? I _think_ I experienced noticed this as well. are you able to reproduce on http://ncase.me/ink/play/?

**Comment by caseyyee** [comment]
Na, it was the same on Mac OS. 
The issue was that VR controls was not updated along with the newer three.js.
Related to this, I also remove head tracking to fix some camera positioning issues.

https://github.com/MozVR/webvr-demos/commit/46d90fef7c8dc399d459d8d1c4ee15d8acc53582
and
https://github.com/MozVR/webvr-demos/commit/6121aa67e837442033da1a0ed341dca1a2af3608
