### ISSUE TITLE
postinstall scripts don't run on windows

### ISSUE THREAD

**Issue by caseyyee** [MozVR/webvr-demos#4]
...

> webvr-demos@1.0.0 postinstall c:\Users\Casey\Developer\webvr-demos
> POLAR_SEA_VIDEOS_URL=http://mozvr.com/projects/polarsea/content/videos/ npm ru
> n syncmedia

'POLAR_SEA_VIDEOS_URL' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\Program Files (x86)\nodejs\node.exe" "c:\Program Files (x8
6)\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! webvr-demos@1.0.0 postinstall: `POLAR_SEA_VIDEOS_URL=http://mozvr.com/p
rojects/polarsea/content/videos/ npm run syncmedia`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webvr-demos@1.0.0 postinstall script 'POLAR_SEA_VIDEOS_UR
L=http://mozvr.com/projects/polarsea/content/videos/ npm run syncmedia'.
npm ERR! This is most likely a problem with the webvr-demos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     POLAR_SEA_VIDEOS_URL=http://mozvr.com/projects/polarsea/content/vid
eos/ npm run syncmedia
npm ERR! You can get their info via:
npm ERR!     npm owner ls webvr-demos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Casey\Developer\webvr-demos\npm-debug.log

**Comment by cvan** [comment]
I guess environment variables don't work. will remove.

**Comment by cvan** [comment]
I bet `export POLAR_SEA_VIDEOS_URL='…' && …` would work instead. but I've opted to just remove the env var entirely: PR #10.

**Comment by caseyyee** [comment]
Ended up using gulp so that we don't have to fiddle around with compatability.
