### ISSUE TITLE
vihart's monkeys submodule not referenced properly

### ISSUE THREAD

**Issue by cvan** [MozVR/webvr-demos#9]
it looks like [Vi Hart's monkeys](https://github.com/vihart/monkeys) was added to this repo's [`public/demos` directory](https://github.com/MozVR/webvr-demos/tree/master/public/demos), but the submodule didn't take.

the submodule looks like it wasn't correctly added.

<hr>

after this has been fixed, this all-in-one command should correctly pull the repo and update the necessary submodules:

``` bash
git pull --rebase && git submodule sync && git submodule update --recursive
```

**Comment by caseyyee** [comment]
Yeah, need to re-add these examples as proper submodules.  For now i have them cloned into the demos folders since there has been adjustments made specifically to work in Horizon.

Will keep open for now, but maybe we should import these as npm modules instead?

**Comment by cvan** [comment]
@caseyyee it looks like you added it: https://github.com/MozVR/webvr-demos/tree/master/demos/vihart

should be fine now to close. I thought we may want to use npm modules, but then I realised we should just keep them in their own repos, serve from GitHub Pages, and use Service Workers. thoughts?
